version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artel_web
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: pnpm dev
services:  web:    build:      context: .      dockerfile: Dockerfile    container_name: artel_web    ports:      - "3000:3000"    volumes:      - .:/app    environment:      - NODE_ENV=development    command: pnpm dev